services:
  mysql:
    image: mysql:8.4
    container_name: mysql
    restart: always
    volumes:
      - ./conf/db/conf.cnf:/etc/mysql/conf.d/my.cnf
      - ./conf/db/conf.sh:/docker-entrypoint-initdb.d/conf.sh
    networks:
      - home
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/data_pswd
      MYSQL_DATABASE: TRANS
      MYSQL_USER: bobi
      MYSQL_PASSWORD: 123
    secrets:
      - data_pswd
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 15

  myadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: myadmin
    depends_on:
      - mysql
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: bobi
      PMA_PASSWORD: 123
    networks:
      - home
    restart: always

  front:
    build: ./web/front/
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - home
    ports:
      - "5173:5173"
    volumes:
      - ./web/front:/app/front  # monte le frontend pour HMR
      - /app/front/node_modules


  gateway:
    build: ./web/back/
    environment:
      DB_USER: "bobi"
      DB_PASSWORD: 123
      DB_NAME: "TRANS"
      DB_HOST: "mysql"
      DB_PORT:  3306
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - home
    ports:
      - "9000:9000"
    volumes:
      - ./web/back/:/app/back/
      - /app/back/node_modules
    secrets:
    - cle_pswd
    - cle_chat
  
  auth:
    build: ./web/back/
    environment:
      DB_USER: "bobi"
      DB_PASSWORD: 123
      DB_NAME: "TRANS"
      DB_HOST: "mysql"
      DB_PORT:  3306
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - home
    ports:
      - "9100:9100"
    volumes:
      - ./web/back/auth:/app/back/auth
      - /app/back/auth/node_modules
    secrets:
    - cle_pswd
    - cle_chat

  chatP_service:
    build: ./web/back/chat/chatP
    environment:
      DB_USER: "bobi"
      DB_PASSWORD: 123
      DB_NAME: "TRANS"
      DB_HOST: "mysql"
      DB_PORT:  3306
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - home
    ports:
      - "9002:9002"
    volumes:
      - ./web/back/chat/chatP:/app/back/chat/chatP                 # monte tout le backend
      - /app/back/chat/chatP/node_modules
    secrets:
    - cle_pswd
    - cle_chat

  chatG_service:
    build: ./web/back/chat/chatG
    environment:
      DB_USER: "bobi"
      DB_PASSWORD: 123
      DB_NAME: "TRANS"
      DB_HOST: "mysql"
      DB_PORT:  3306
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - home
    ports:
      - "9001:9001"
    volumes:
      - ./web/back/chat/chatG:/app/back/chat/chatG                 # monte tout le backend
      - /app/back/chat/chatG//node_modules
    secrets:
    - cle_pswd
    - cle_chat

  user_service:
    build: ./web/back/user
    environment:
      DB_USER: "bobi"
      DB_PASSWORD: 123
      DB_NAME: "TRANS"
      DB_HOST: "mysql"
      DB_PORT:  3306
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - home
    ports:
      - "9003:9003"
    volumes:
      - ./web/back/user:/app/back/user
      - /app/back/user/node_modules
    secrets:
    - cle_pswd

  game:
    build: ./web/back/game
    environment:
      DB_USER: "bobi"
      DB_PASSWORD: 123
      DB_NAME: "TRANS"
      DB_HOST: "mysql"
      DB_PORT:  3306
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - home
    ports:
      - "9004:9004"
      - "2567:2567"
    secrets:
      - cle_pswd
    volumes:
      - ./web/back/gameServer:/app/back/gameServer
      - /app/back/gameServer/node_modules
      - ./web/back/morp:/app/back/morp
      - /app/back/morp/node_modules

secrets:
  data_pswd:
    file: ./conf/secrets/data_pswd
  cle_chat:
    file: ./conf/secrets/cle_chat
  cle_pswd:
    file: ./conf/secrets/cle_pswd

networks:
  home:
    driver: bridge
